create table if not exists `yi_task` (
    `id` int(11) unsigned not null auto_increment,
    `taskStatus` tinyint(2) not null comment '任务状态: -1:撤销, 0:创建中, 1:创建成功，未付款, 2:创建成功，已付款待审核， 3：审核成功， 4：任务全部完成',
    `taskUserId` int(11) not null comment '任务用户id',
    `taskShopName` varchar(32) not null default '' comment '任务店铺名称',
    `taskShopId` int(11) not null comment '任务店铺id',
    `taskPV` int(11) not null default '0' comment '任务使用流量数',
    `taskPlatform` varchar(32) not null default '' comment '任务平台: taobao,tmall,jd',
    `taskType` varchar(32) not null default '' comment '任务类型: dingdan, juhuasan, zhitongche',
    `taskHeight` decimal(4,2) not null comment '商品重量',
    `taskName` varchar(256) not null default '' comment '商品名',
    `taskUrl` varchar(512) not null default '' comment '商品链接',
    `taskAllCoin` decimal(10, 2) not null default '0' comment '总费用',
    `taskAllMoney` decimal(10, 2) not null default '0' comment '总押金',
    `taskMoney` decimal(10, 2) not null default '0' comment '商品价格',
    `taskCount` int(4) not null default '0' comment '商品购买数量',
    `taskSearchMoney` decimal(10,2) not null default '0' comment '商品搜索价格',
    `taskPriceStart` decimal(10,2) not null default '0' comment '商品搜索价格开始',
    `taskPriceEnd` decimal(10,2) not null default '0' comment '商品搜索价格结束',
    `taskTotalCount` int(4) not null default '0' comment '总单数',
    `taskPcCount` int(4) not null default '0' comment '电脑单数',
    `taskPhoneCount` int(4) not null default '0' comment '移动端单数',
    `taskTotalMoney` decimal(10,2) not null default '0' comment '总押金',
    `taskPromise` decimal(6,2) not null default '0' comment '退款保证金',
    `taskTotalPromise` decimal(6,2) not null default '0' comment '总退款保证金',
    `taskFee` decimal(4,2) not null default '0' comment '刷一单的费用',
    `taskTotalFee` decimal(4,2) not null default '0' comment '总的刷单费用',
    `taskTransportFee` decimal(4,2) not null default '0' comment '快递费',
    `taskPhone` decimal(6,2) not null default '0' comment '移动端附加费',
    `taskIsPayback` bool not null comment '是否平台返款',
    `taskPayback` decimal(6,2) not null default '0' comment '平台返款服务费',
    `taskSpeed` decimal(6,2) not null default '0' comment '提升完成任务速度',
    `taskIsExtendFee` bool not null comment '是否平台加赏任务佣金',
    `taskExtendFee` decimal(6,2) not null default '0' comment '加赏单任务佣金',
    `taskIsInterval` bool not null comment '是否任务发布间隔',
    `taskIntervalTime` int(6) not null default '0' comment '每隔多久发布',
    `taskIntervalCount` int(2) not null default '0' comment '间隔发布几个',
    `taskInterval` decimal(6,2) not null default '0' comment '间隔发布的费用',
    `taskCycleTime` int(2) not null default '0' comment '延长买家购物周期',
    `taskTotalCycle` decimal(4, 2) not null default '0' comment '延长买家购物周期总共费用',
    `taskIsGoodComment` bool not null comment '是否优质好评',
    `taskGoodCommentCount` tinyint(2) not null default '0' comment '好评个数',
    `taskGoodCommentFee` decimal(4,2) not null default '0' comment '好评费用',
    `taskGoodComment` text not null comment '好评内容',
    `taskTransport` varchar(20) not null default '' comment '快递类型',
    `taskTips` varchar(256) not null default '' comment '下单提示',
    `taskPosition` varchar(12) not null default '' comment '地点',
    `taskTag1` varchar(12) not null default '' comment '规格1',
    `taskTag2` varchar(12) not null default '' comment '规格2',
    `taskComment` varchar(512) not null default '' comment '备注信息',
    `taskCreateTime` timestamp not null default current_timestamp,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;